import { GoogleGenAI } from "@google/genai"
import { NextResponse } from 'next/server'

if (!process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
  throw new Error("GOOGLE_GENERATIVE_AI_API_KEY environment variable is not set.")
}

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY })

export async function POST(req: Request) {
  try {
    const body = await req.json()
    const { prompt, numberOfImages = 1, aspectRatio = '1:1' } = body

    if (!prompt) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      )
    }

    console.log('Generating image with prompt:', prompt)

    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: numberOfImages,
        outputMimeType: 'image/jpeg',
        aspectRatio: aspectRatio,
      },
    })

    if (response.generatedImages && response.generatedImages.length > 0) {
      const images = response.generatedImages.map((img, index) => {
        const base64ImageBytes: string = img.image.imageBytes
        return {
          id: `${Date.now()}-${index}`,
          dataUrl: `data:image/jpeg;base64,${base64ImageBytes}`,
          prompt: prompt,
          createdAt: new Date().toISOString()
        }
      })

      return NextResponse.json({
        success: true,
        images: images
      })
    } else {
      throw new Error('No image was generated by the API.')
    }
  } catch (error) {
    console.error("Error calling Google GenAI API:", error)
    return NextResponse.json(
      {
        error: "Failed to generate image",
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}
